/**
 * POST /api/ai/finetune
 * Fine-tuning Studio (Projects #101, #103)
 * 
 * NOTE: GPU-intensive tasks can't run on HF Space (cpu-basic).
 * This route creates a finetune CONFIG that the user can run locally
 * or on a GPU instance (RunPod, Colab, etc.).
 */

import { NextRequest, NextResponse } from 'next/server';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json() as {
      model: string;          // e.g. "deepseek-ai/deepseek-r1"
      method: 'full' | 'lora' | 'qlora' | 'grpo';
      dataset: string;        // HuggingFace dataset name or URL
      epochs?: number;
      learningRate?: number;
      batchSize?: number;
      maxSeqLength?: number;
    };

    if (!body.model || !body.method) {
      return NextResponse.json({ error: 'model and method required' }, { status: 400 });
    }

    // Generate a finetune script the user can run on a GPU instance
    const script = generateFinetuneScript(body);
    const config = {
      ...body,
      epochs: body.epochs || 3,
      learningRate: body.learningRate || 2e-5,
      batchSize: body.batchSize || 4,
      maxSeqLength: body.maxSeqLength || 2048,
      estimatedVRAM: estimateVRAM(body),
      recommendedGPU: recommendGPU(body),
    };

    return NextResponse.json({
      success: true,
      config,
      script,
      instructions: `1. Copy the script to a GPU instance (RunPod, Colab, etc.)
2. pip install -r requirements.txt
3. python finetune.py
4. Upload the model to HuggingFace Hub
5. Add the model ID to Anzaro's custom models`,
    });
  } catch (error) {
    return NextResponse.json({ error: 'Finetune config failed' }, { status: 500 });
  }
}

function generateFinetuneScript(config: any): string {
  const methodConfig = config.method === 'grpo' ? 'GRPOConfig' : config.method === 'lora' ? 'LoraConfig' : 'QLoraConfig';

  return `# Anzaro Fine-tuning Script — ${config.method.toUpperCase()}
# Generated by Anzaro AI
# Model: ${config.model}
# Dataset: ${config.dataset}

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
${config.method === 'lora' || config.method === 'qlora' ? "from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training" : ""}
from trl import SFTTrainer, SFTConfig${config.method === 'grpo' ? ', GRPOTrainer, GRPOConfig' : ''}
from datasets import load_dataset

# ── Config ──
MODEL_NAME = "${config.model}"
DATASET = "${config.dataset}"
EPOCHS = ${config.epochs || 3}
LR = ${config.learningRate || 2e-5}
BATCH = ${config.batchSize || 4}
MAX_LEN = ${config.maxSeqLength || 2048}
OUTPUT = "./anzaro-finetuned"

# ── Load model ──
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.bfloat16,
    device_map="auto",
)

${config.method === 'lora' || config.method === 'qlora' ? `
# ── LoRA/QLoRA ──
model = prepare_model_for_kbit_training(model)
lora_config = LoraConfig(
    r=16, lora_alpha=32, lora_dropout=0.05,
    target_modules=["q_proj", "v_proj", "k_proj", "o_proj"],
    task_type="CAUSAL_LM",
)
model = get_peft_model(model, lora_config)
` : ""}

# ── Load dataset ──
dataset = load_dataset(DATASET)

# ── Train ──
${config.method === 'grpo' ? `
training_config = GRPOConfig(
    output_dir=OUTPUT,
    num_train_epochs=EPOCHS,
    learning_rate=LR,
    per_device_train_batch_size=BATCH,
    max_length=MAX_LEN,
)
trainer = GRPOTrainer(
    model=model,
    args=training_config,
    train_dataset=dataset["train"],
)
` : `
training_config = SFTConfig(
    output_dir=OUTPUT,
    num_train_epochs=EPOCHS,
    learning_rate=LR,
    per_device_train_batch_size=BATCH,
    max_seq_length=MAX_LEN,
    save_strategy="epoch",
)
trainer = SFTTrainer(
    model=model,
    args=training_config,
    train_dataset=dataset["train"],
    processing_class=tokenizer,
)
`}

trainer.train()
trainer.save_model(OUTPUT)
print(f"✅ Model saved to {OUTPUT}")
print(f"Upload with: huggingface-cli upload your-username/anzaro-finetuned {OUTPUT}")
`;
}

function estimateVRAM(config: any): string {
  const base = {
    full: '40-80GB (needs A100 80GB or 2x A100 40GB)',
    lora: '16-24GB (single A100 or RTX 4090)',
    qlora: '8-12GB (RTX 3090/4090 or T4)',
    grpo: '24-48GB (A100 recommended)',
  };
  return base[config.method as keyof typeof base] || 'Unknown';
}

function recommendGPU(config: any): string {
  const recs = {
    full: 'NVIDIA A100 80GB or 2x A100 40GB',
    lora: 'NVIDIA A100 40GB or RTX 4090 24GB',
    qlora: 'NVIDIA RTX 3090 24GB or T4 16GB',
    grpo: 'NVIDIA A100 40GB+',
  };
  return recs[config.method as keyof typeof recs] || 'NVIDIA GPU with 16GB+ VRAM';
}

export async function GET() {
  return NextResponse.json({
    name: 'Fine-tuning Studio',
    methods: ['full', 'lora', 'qlora', 'grpo'],
    note: 'GPU tasks run externally. This route generates finetune scripts to run on GPU instances.',
  });
}
