import type { OnboardingQuestion } from './types'

// 18 adaptive questions (within the 15-30 range required by Phase 3.1)
// Mix of demographic + psychological + preference + driver categories
export const ONBOARDING_QUESTIONS: OnboardingQuestion[] = [
  {
    id: 'name',
    question: 'First, what should I call you?',
    questionAr: 'أول حاجة، أناديك بإيه؟',
    category: 'demographic',
    inputType: 'text',
  },
  {
    id: 'age',
    question: 'How old are you?',
    questionAr: 'عندك كام سنة؟',
    category: 'demographic',
    inputType: 'text',
  },
  {
    id: 'occupation',
    question: 'What do you do for a living?',
    questionAr: 'بتشتغل إيه؟',
    category: 'demographic',
    inputType: 'text',
  },
  {
    id: 'dialect',
    question: 'Which dialect do you prefer me to speak in?',
    questionAr: 'تحب أكلمك بأي لهجة؟',
    category: 'demographic',
    inputType: 'choice',
    options: ['Egyptian (مصري)', 'Khaleeji (خليجي)', 'Levantine (شامي)', 'MSA (فصحى)', 'English'],
    optionsAr: ['مصري', 'خليجي', 'شامي', 'فصحى', 'إنجليزي'],
  },
  {
    id: 'leadership',
    question: 'In a group, do you naturally take the lead or support from behind?',
    questionAr: 'في أي جروب، بتنطق تقود ولا بتفضل تدعم من ورا؟',
    category: 'psychological',
    inputType: 'scale',
    traitKey: 'leadership',
  },
  {
    id: 'stubbornness',
    question: 'Once you decide something, how hard is it to change your mind?',
    questionAr: 'لما تقرر حاجة، قد إيه بيكون صعب ترفض رأيك؟',
    category: 'psychological',
    inputType: 'scale',
    traitKey: 'stubbornness',
  },
  {
    id: 'analytical',
    question: 'When facing a problem, do you trust logic or your gut feeling more?',
    questionAr: 'أمام مشكلة، بتثق أكتر في المنطق ولا في إحساسك؟',
    category: 'psychological',
    inputType: 'scale',
    traitKey: 'analytical',
  },
  {
    id: 'emotional',
    question: 'Do decisions in your life usually come from the head or the heart?',
    questionAr: 'قراراتك في حياتك بتيجي من الدماغ ولا من القلب؟',
    category: 'psychological',
    inputType: 'scale',
    traitKey: 'emotional',
  },
  {
    id: 'discipline',
    question: 'How strictly do you stick to your daily routines and plans?',
    questionAr: 'قد إيه بتلتزم بروتينك وخططك اليومية؟',
    category: 'psychological',
    inputType: 'scale',
    traitKey: 'discipline',
  },
  {
    id: 'sociability',
    question: 'After a long day, do you recharge alone or with people?',
    questionAr: 'بعد يوم طويل، بتشحن طاقتك لوحدك ولا مع ناس؟',
    category: 'psychological',
    inputType: 'scale',
    traitKey: 'sociability',
  },
  {
    id: 'humor',
    question: 'How much do you appreciate humor even in serious moments?',
    questionAr: 'قد إيه بتحب النكتة حتى في اللحظات الجادة؟',
    category: 'psychological',
    inputType: 'scale',
    traitKey: 'humor',
  },
  {
    id: 'driver_success',
    question: 'What drives you more: building something lasting, or winning in the moment?',
    questionAr: 'إيه بيحركك أكتر: تبني حاجة تدوم، ولا تكسب اللحظة دي؟',
    category: 'driver',
    inputType: 'choice',
    options: ['Building something lasting', 'Winning in the moment', 'Both equally'],
    optionsAr: ['أبني حاجة تدوم', 'أكسب اللحظة دي', 'الاتنين ب نفس القدر'],
  },
  {
    id: 'driver_fear',
    question: 'What is the one thing you never want to feel?',
    questionAr: 'إيه الحاجة اللي مابتحبش تحس بيها أبداً؟',
    category: 'driver',
    inputType: 'choice',
    options: ['Being stuck / no progress', 'Being misunderstood', 'Letting people down', 'Losing control'],
    optionsAr: ['أبقى مكان روحي', 'محدش يفهمني', 'أخذّل ناس', 'أخسر السيطرة'],
  },
  {
    id: 'preference_communication',
    question: 'How do you like to receive information?',
    questionAr: 'بتحب أقولك المعلومة إزاي؟',
    category: 'preference',
    inputType: 'choice',
    options: ['Short & direct', 'Detailed & explained', 'Visual / examples', 'Story-driven'],
    optionsAr: ['قصير ومباشر', 'مفصل وش راح', 'أمثلة وصور', 'على لسان قصة'],
  },
  {
    id: 'preference_morning',
    question: 'Are you a morning person or a night person?',
    questionAr: 'إنت من الناس اللي الصبح ولا الليل؟',
    category: 'preference',
    inputType: 'choice',
    options: ['Early morning', 'Late night', 'Afternoon peak', 'Flexible'],
    optionsAr: ['بدري الصبح', 'آخر الليل', 'الضهر', 'مرن'],
  },
  {
    id: 'trigger_stress',
    question: 'When stressed, what helps you most?',
    questionAr: 'لما بتبقى مضغوط، إيه اللي بيريّحك أكتر؟',
    category: 'driver',
    inputType: 'choice',
    options: ['Silence & space', 'Talking it out', 'Music / Quran', 'Action & movement'],
    optionsAr: ['سكتة وخلوة', 'أكلم حد', 'موسيقى/قرآن', 'حركة وأكشن'],
  },
  {
    id: 'goal_3months',
    question: 'If we worked together for 3 months, what would success look like for you?',
    questionAr: 'لو شغلنا مع بعض 3 شهور، النجاح شكله إيه عندك؟',
    category: 'driver',
    inputType: 'text',
  },
  {
    id: 'anything_else',
    question: 'Anything else you want Anzaro to know about you?',
    questionAr: 'في حاجة تاني عايز آنزارو يعرفها عنك؟',
    category: 'preference',
    inputType: 'text',
  },
]
