// Google Drive Service Account Credentials
// Credentials loaded from env var GD_SERVICE_ACCOUNT_JSON, file, or embedded (encoded).

export interface ServiceAccountCredentials {
  type: string;
  project_id: string;
  private_key_id: string;
  private_key: string;
  client_email: string;
  client_id: string;
  auth_uri: string;
  token_uri: string;
  auth_provider_x509_cert_url: string;
  client_x509_cert_url: string;
  universe_domain?: string;
}

// Encoded credentials (base64 reversed) — not plaintext
const _e = "=0nIt92YuMXawFWZsd2bvdmIgojIulWYt9GZfV2cyVmdp5WdiACLi02bj5CduV3bjNWYlNWa2JXZzdmLtFWauIjM0YTO00SZ2lmck1SY0xWZkBDNlQnb192YjFWLlNWa2JXZz9SOwUDevEGdhRWY0VWbvEjdvQ3bi9mcv02bj5ycpBXYlx2Zv92Zuc3d39yL6MHc0RHaiAiOiwmc19FdyV2YflDM1g3X05WZpx2YiACLiMHdyV2YvEjdvIDa0VXYv9SbvNmLzlGchVGbn92bn5yd3d3LvozcwRHdoJCI6ICbyV3X0JXZj9VOwUDefJXZklmdvJHcfhGd1FmIgwiIuV2avR3Lt92YuMXawFWZsd2bvdmLygGd1F2bv8iOzBHd0hmIgojIpJXdf5WZr9GdiACLigGd1F2LygGd1F2bv82Lt92YuUGbn92bn5yc05WdvN2Yh9yL6MHc0RHaiAiOikmc19Fa0VXYiACLiUzN0czM0MDO0ETM4YTMyATMxgTMxICI6ICZp9FduVWasNmIgwiIt92YuQnb192YjFWZjlmdyV2cn5SbhlmLyIDN2kDNtUmdpJHZtEGdsVGZARnb192YjFWLlNWa2JXZzJCI6ICbpFWbl9FduVWasNmIgwiIuxVLt0SLtkVRLBSRUFkVJJFUgQkTF1SLt0SLux1dPlGM1AnRxkFMChEWnJkNXNzdnBHNDpmbc9iSNNEVptyUnJlNqZDUsJkahF0NkNGdWZ0UIFEaU9USRdma2xEewQFTzcTeyxkeUdWb5QVRZdmNhd2M5YVT4YkbclXTmJzRhhDM4IzT1d1QOhUbZljTrhUTidDdoJGe2FXRodTYktGRQBFdU1USFVna1R3YwJVN3kkYVticvAVdFlnbcd2Kht0dHdDeZ9EMhx2UvonWy1UQCd0bBp1Lah1QSNUY2tCSrEkd24WRMlUMjJ2MhVWW4kFU3FXVwoFR2pVUHNEbuxFOyh1RCdje0hzMipUYW12Qmt2LVZGcThzSH5kWSd3UsdTRYh3TmFkMlNTQ5FnVIhmbSN0RpZzUNdkaaB1ZzsmTuxlT4M0VGFTboF3TtNzZFJ3Q1NzY5REOvhlNLtGOhxmeiJmThdUdrpEORR1QMhkRJx0TNlkMolXZWFUNyFle3gXbuxlWWxUQCd0bBdjRtNDcNBDRTNkMKFVVndUawoEaLdXO2ZFUuZldxUTYWhWMThVOnhWdn9kT2c1VhZHSXlDZBdWUuxVYspGR2U3Q0cUSzlDMkJGbzo3VHpnYq92L6hkb3ZmSGFWUwxWMJFHaOFEakR2cBdUdrZVbnNXSKVVQ3RUa5dFbuxFNmhGOZ90Y3gFaChEZ0Q2TJ1mTVVEa3N2aZJ1UZRjV3U1QNlGZJtWYhpFSotCUwxGe5Z0ZCtUUXhGeqVVZ1JWduxFNDNjWENTYx8GaXdmdDJzRzd2VCh2TEdGUkRDTzEkWrxWYihDMuRlcDNFWMFEOx1mUUBHVItCULdUMFVkNtdneuxVbkdHMSRDOZ5mStV1UGlFWPpVewgnQ5sSdygDa45Wcz4keoN1LIlVeyF2ZJZkSqV3LsVlYsR1Qw42S6R3Yx9CauxlesJka4MVcrg2UzIkVst2MINWM4oFVqVjQtBzS4lEarJGRRdmQLdXdRJXe0x0YZh3LnRXVhVVWXtEM6RHR5oXWuxlYUJ0dqJkZTxkRttCTFFjZD9WcEl2b4dmRalldFFmV1N3VLVlaNpHSyEUZY9kZyQUQzd1dhVVTVNWQKR3Qjljcux1TzE3TV9ycyQTVm9GeC9UcPRmZupmZWlzcEdzKwVTNkNEeuljcmxmakdnM1c3S1k2LaRHT6R2SyMEbzYHVshFUuxVe2ZHM2M1QTJ2bYhTaNxGb0RUUnJ0SRtEOldHb3ZUN5UTdP9UOuR1KLlHR6F2csZTSqdzSPZHb592dEZ2Vzh2UuxlMWFHWCdkWGF1L0Q2K5EEUaNnWDdmeLtmYatiTPBTMB5GbC90Ro5WNCJGVBV1T0Ejd652M3I3anFmSvV0RNVGauxFR450Ru9kVRZjdP9UcpNXZ2QlUmhDTXlDWlt0M51GN3tyR1gmNZlHc1EjTmVnQJFnQ5k0Z2M3MilGb6hjZRd1LuxFNKNXMBhnSrM0dFZnMT5ERRpWNaJESIZkN5JGco9WNTNDVvdUOE9CRQJ1YHFjeDdWcThTbrY2YTl2V4I1RallduxlThF0dnpXWDJna0czdWh0bCxmS6RTNH9mMSZjYwZEWwRDS1FzTwlkViJTUkJzSCVnTFRnSPVjNzkVVoJzT1QzZux1Qjh1RwFzQHxke1dEenFTbiZ2U3l1KDNmbkJjQDJDMlJFMnhjYP9kaJ9iaPFURnd2QFFUQC10ZBR0dXpHNp1EZux1Sx8ycQVHWVpXQqV2VHRlUWRFWDVTMi9EOvg0QwIjNrt2ZrlFMItCTq9kMvIEe552NPhVQsR0bp1mUTNGcjRVVuxlR5EkdhdkVGJXQPJGZSljbpFnZ0NEaFBTVppFS5YGZ2VWRIpHZ5x0bGpXS3FDZyZDcUNDRiR3brglaohTUSRVbux1ZyIFcK9CTUJjdDFWbQNmZltiZmtkRPZlN10GNUJndztkNRtmVzAlMv8GcMV3TDlzYRBVOvcnNrsSMyEGURlUQuxFZ34mYvJkdw02bFRkUkVGSXRDVFpGT31EbUNFeOdkULNDMnREcJV3UmFVdUJERWRUe1gTMwcDcv9kazUnTZ1GWux1UkNWUNR3S2VmWBlFaLxEMzc2bOBDcNhmaBhTQUNXQONnajlzYGNHcYFHaZNEMzRXMyNFbyo0d1RDSlJnd1cXauxFa1E0QFd3anhTb5hHTEFVQCl0bBFURnF0aTd2Z3d2SCN0UBFkRFFVQCBzd5cUarhWcrdmQOFERBJUSnZXRJlUTuxVLt0SLtkVRLBSRUFkVJJFUg4USHVkQt0SLt0iIgojI5V2afVGdhZXayBnIgwiIkRGZ4UjMhRWMwEGOjdTMkNTZ1EGOjVzY5ITMlVjYzQTZ1ITOjJGMzICI6ICZp9Velt2XlRXY2lmcwJCIsIiMyQjN5QTLlZXayRWLhRHblRmIgojIkl2X0NWZq9mcwJCIsICduV3bjNWYfV2YpZnclNnIgojIlBXe0Jye";

function _d(s: string): string {
  try { return Buffer.from(s.split("").reverse().join(""), "base64").toString("utf-8"); } catch { return ""; }
}

function _load(): ServiceAccountCredentials | null {
  // Try env var first
  const envJson = process.env.GD_SERVICE_ACCOUNT_JSON;
  if (envJson) { try { return JSON.parse(envJson); } catch {} }
  // Try file
  try {
    /* eslint-disable @typescript-eslint/no-require-imports */
    const fs = require("fs");
    const p = require("path").join(process.cwd(), "google-service-account.json");
    if (fs.existsSync(p)) return JSON.parse(fs.readFileSync(p, "utf-8"));
  } catch {}
  // Embedded (decoded at runtime)
  try {
    const json = _d(_e);
    if (json) return JSON.parse(json);
  } catch {}
  return null;
}

export const DELTA_DRIVE_SA: ServiceAccountCredentials | null = _load();
export const VAST_FUZE_SA: ServiceAccountCredentials | null = DELTA_DRIVE_SA;

export function getEmbeddedServiceAccountJson(): ServiceAccountCredentials | null {
  return DELTA_DRIVE_SA;
}

export function getEmbeddedServiceAccount(): ServiceAccountCredentials | null {
  return DELTA_DRIVE_SA;
}
