// ═══════════════════════════════════════════════════════════════════════
// POST /api/generate-anzaro-test
// ═══════════════════════════════════════════════════════════════════════
// Stress-test endpoint for the Anzaro Limitless Pipeline.
// Triggers the entire orchestrator + designer + printer with test data
// to prove it can autonomously loop through tools and output a PDF.
// ═══════════════════════════════════════════════════════════════════════

import { NextRequest, NextResponse } from 'next/server';
import { runAnzaroOrchestrator, type AnzaroDocumentInput } from '@/lib/pdf-engine/anzaro-orchestrator';
import { enhanceAnzaroHTML } from '@/lib/pdf-engine/anzaro-designer';
import { renderHTMLToPDFAnzaro, isAnzaroPrinterAvailable } from '@/lib/pdf-engine/printer';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';
export const maxDuration = 300; // 5 minutes — Anzaro needs time for unlimited tool calls

export async function POST(request: NextRequest) {
  const startTime = Date.now();

  try {
    const body = await request.json().catch(() => ({})) as {
      topic?: string;
      description?: string;
      targetPages?: number;
      language?: 'ar' | 'en';
      style?: 'tech' | 'medical' | 'academic' | 'creative';
    };

    // ── Test data (used if no body provided) ──
    const input: AnzaroDocumentInput = {
      title: body.topic || 'Anzaro Test Document',
      topic: body.topic || 'تطبيقات الذكاء الاصطناعي في الطب الحديث',
      description: body.description || 'وثيقة شاملة Generated by Anzaro — بحث عميق + صور + رسوم بيانية + مخططات',
      targetPages: body.targetPages || 5,
      language: body.language || 'ar',
      style: body.style || 'tech',
      userDocuments: [],
    };

    console.log('[Anzaro Test] Starting limitless pipeline...');
    console.log('[Anzaro Test] Topic:', input.topic);
    console.log('[Anzaro Test] Target pages:', input.targetPages);

    // ── Phase 0: Check if Playwright is available ──
    const playwrightAvailable = await isAnzaroPrinterAvailable();
    if (!playwrightAvailable) {
      return NextResponse.json({
        success: false,
        error: 'Playwright is not available on this server',
      }, { status: 500 });
    }

    // ── Phase 1+2: Run the Anzaro Omni-Orchestrator ──
    const orchestratorOutput = await runAnzaroOrchestrator(input);

    console.log('[Anzaro Test] Orchestrator complete:');
    console.log('  Tool calls:', orchestratorOutput.toolCallCount);
    console.log('  Assets:', orchestratorOutput.assets.length);
    console.log('  HTML size:', orchestratorOutput.html.length);

    // ── Phase 2.5: Enhance HTML with premium shell ──
    const finalHTML = enhanceAnzaroHTML(orchestratorOutput, input);

    // ── Phase 3: Print to PDF via Memory-Safe Playwright Mutex Queue ──
    const filename = `anzaro-test-${Date.now()}.pdf`;
    const printResult = await renderHTMLToPDFAnzaro({
      html: finalHTML,
      filename,
      format: 'A4',
      printBackground: true,
    });

    const totalTimeMs = Date.now() - startTime;

    if (!printResult.success) {
      return NextResponse.json({
        success: false,
        error: 'PDF rendering failed',
        detail: printResult.error,
        orchestratorStats: {
          toolCalls: orchestratorOutput.toolCallCount,
          assets: orchestratorOutput.assets.length,
          htmlSize: orchestratorOutput.html.length,
        },
        totalTimeMs,
        logs: orchestratorOutput.logs,
      }, { status: 500 });
    }

    // ── Success — return the PDF URL + stats ──
    const pdfUrl = `/api/pdf/serve/${filename}`;

    return NextResponse.json({
      success: true,
      pdfUrl,
      fileSize: printResult.fileSize,
      renderTimeMs: printResult.renderTimeMs,
      totalTimeMs,
      stats: {
        toolCalls: orchestratorOutput.toolCallCount,
        assetsGenerated: orchestratorOutput.assets.length,
        assetsByType: {
          images: orchestratorOutput.assets.filter((a: any) => a.type === 'image').length,
          charts: orchestratorOutput.assets.filter((a: any) => a.type === 'chart').length,
          diagrams: orchestratorOutput.assets.filter((a: any) => a.type === 'diagram').length,
          searchResults: orchestratorOutput.assets.filter((a: any) => a.type === 'search_result').length,
        },
        pageCount: orchestratorOutput.plan.pageCount,
        sectionCount: orchestratorOutput.plan.sections.length,
        htmlSize: finalHTML.length,
      },
      logs: orchestratorOutput.logs,
    });

  } catch (error) {
    const errorMsg = error instanceof Error ? error.message : String(error);
    console.error('[Anzaro Test] Fatal error:', errorMsg);
    return NextResponse.json({
      success: false,
      error: 'Anzaro pipeline crashed',
      detail: errorMsg,
      totalTimeMs: Date.now() - startTime,
    }, { status: 500 });
  }
}

// ═══════════════════════════════════════════════════════════════════════
// GET — quick health check
// ═══════════════════════════════════════════════════════════════════════

export async function GET() {
  const playwrightAvailable = await isAnzaroPrinterAvailable();
  return NextResponse.json({
    status: 'ok',
    playwrightAvailable,
    message: 'Anzaro Omni-Engine is ready. POST with { topic, targetPages, style } to generate a PDF.',
    tools: [
      'web_search', 'read_web_page',
      'generate_image', 'image_search',
      'generate_chart', 'generate_mermaid',
      'code_interpreter', 'generate_text',
      'translate', 'design_layout',
    ],
  });
}
