/**
 * MCP Tool — Document Generator
 * =============================
 * توليد مستند Word / Excel / PowerPoint احترافي (محتوى بـ GLM + توليد binary).
 *
 * الـ binary بيرجع base64 عشان يقدر الـ agent يباسطه للعميل.
 */
import type { MCPTool } from "../types";
import { generateDocument } from "@/lib/integrations/document-generator";

export const documentGenerateTool: MCPTool = {
  name: "document_generate",
  description:
    "Generate a professional Word (.docx), Excel (.xlsx), or PowerPoint (.pptx) document about any topic. Content is generated by GLM-5.2 and rendered into a binary file. Returns base64-encoded file content.",
  parameters: {
    type: "object",
    properties: {
      topic: {
        type: "string",
        description: "The topic of the document (e.g. 'تقرير عن الذكاء الاصطناعي').",
      },
      type: {
        type: "string",
        description: "Document type.",
        enum: ["docx", "xlsx", "pptx"],
        default: "docx",
      },
      language: {
        type: "string",
        description: "Content language.",
        enum: ["ar", "en"],
        default: "ar",
      },
    },
    required: ["topic", "type"],
  },
  async execute(params) {
    const topic = String(params.topic || "").trim();
    const type = (String(params.type || "docx").toLowerCase().trim()) as "docx" | "xlsx" | "pptx";
    const language = (String(params.language || "ar").toLowerCase().trim() as "ar" | "en");

    if (!topic) {
      return { success: false, error: "topic مطلوبة" };
    }

    if (!["docx", "xlsx", "pptx"].includes(type)) {
      return { success: false, error: `type غير مدعوم: ${type}` };
    }

    const result = await generateDocument({ topic, type, language });

    if (!result.success || !result.buffer) {
      return { success: false, error: result.error || "فشل توليد المستند" };
    }

    const base64 = `data:${result.mimeType};base64,${result.buffer.toString("base64")}`;

    return {
      success: true,
      data: {
        topic,
        type,
        language,
        filename: result.filename,
        mimeType: result.mimeType,
        sizeBytes: result.buffer.length,
        base64,
      },
    };
  },
};
